from keyboards.start_client_keyboard import client_keyboard
from keyboards.inline_info_client_keyboard import inline_client_keyboard_info, inline_client_keyboard_chapter
from keyboards.tests_client_keyboard import tests_client_keyboard